export default {
  documentationUrl: "",
  clientsUrl: "",
  clientScopesUrl: "",
  realmRolesUrl: "",
  usersUrl: "",
  groupsUrl: "",
  orgGroupsUrl: "",
  sessionsUrl: "",
  eventsUrl: "",
  realmSettingsUrl: "",
  authenticationUrl: "",
  identityProvidersUrl: "",
  userFederationUrl: "",
  documentation: "",
  guides: "",
  community: "",
  blog: "",
  workflowsUrl: "",
};
